# Generated by Django 5.1.7 on 2025-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='adress',
            field=models.CharField(default='No address', max_length=255),
        ),
    ]
