# Generated by Django 5.1.7 on 2025-03-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customuser',
        ),
    ]
